Decode the ouput of Popen before applying `split'
In Python 3, attempting to split the "blob" returned by Popen causes

  TypeError: Type str doesn't support the buffer API

To avoid that error, we properly specify the encoding.  If we can't
detect the encoding, we resort to forcing UTF-8.

Change-Id: If195659c332b39916c9b0596f1390db8cbcbdcb2
Signed-off-by: Mario Domenech Goulart <mario@ossystems.com.br>